---
all:
  children:
    spark_cluster:
      children:
        master:
          hosts:
            spark-master:
              ansible_host: 34.140.196.244

        workers:
          hosts:
            spark-worker-1:
              ansible_host: 35.195.54.163
            spark-worker-2:
              ansible_host: 34.52.168.22

        edge:
          hosts:
            spark-edge:
              ansible_host: 35.187.85.103

  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/spark-cluster-key
    ansible_python_interpreter: /usr/bin/python3
