---
all:
  children:
    spark_cluster:
      children:
        master:
          hosts:
            spark-master:
              ansible_host: 35.205.44.248

        workers:
          hosts:
            spark-worker-1:
              ansible_host: 104.155.19.190
            spark-worker-2:
              ansible_host: 34.14.12.222

        edge:
          hosts:
            spark-edge:
              ansible_host: 146.148.117.98

  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/spark-cluster-key
    ansible_python_interpreter: /usr/bin/python3
