---
all:
  children:
    spark_cluster:
      children:
        master:
          hosts:
            spark-master:
              ansible_host: 10.0.0.10

        workers:
          hosts:
            spark-worker-1:
              ansible_host: 10.0.0.11
            spark-worker-2:
              ansible_host: 10.0.0.12
            spark-worker-3:
              ansible_host: 10.0.0.13

        edge:
          hosts:
            spark-edge:
              ansible_host: 10.0.0.20

  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/spark-cluster-key
